# Use a base image with Python installed
FROM python:3.11-slim

# Set a working directory in the container
WORKDIR /app

# Install VTK dependencies
RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libxrender1 \
    libxtst6 \
    libxi6 \
    libx11-6 \
    libxext6 \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY backend/ .

CMD ["uvicorn","api:app","--host","0.0.0.0","--port","8001"]